serve: 
  port: 5000
  cors: 
    origin: "http://localhost:3000"
    allowedHeaders:
      - "Content-Type"
    credentials: true

sources:
  - name: UserService
    handler:
      graphql:
        endpoint: ${USER_SERVICE_URL}/graphql
  - name: CourseService
    handler:
      graphql:
        endpoint: ${COURSE_SERVICE_URL}/graphql
  - name: ResourceBoxService
    handler:
      graphql:
        endpoint: ${RESOURCE_BOX_SERVICE_URL}/graphql